### ISSUE TITLE
doesn't work when _scrollingContainer is enabled

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-keepScrollPosition#4]
presumably because it's no longer the `window` that's scrolling, it's `#app` that is.

Look at [this bit of code](https://github.com/adaptlearning/adapt_framework/blob/654c7b93a446445e8ae4a5e16918086d03dd3794/src/core/js/scrolling.js#L43-L73) I'm guessing that the simplest fix would be to switch to using JQuery to get the vertical scroll position...?

**Comment by oliverfoster** [comment]
exactly that
